[package]
name = "hello_kafka"
version = "0.1.0"
authors = ["Christopher Saunders <topher6345@gmail.com>"]

[dependencies]
kafka = "0.7"
error-chain = "0.11.0"
getopts = "0.2.17"
log = "0.4.0"
env_logger = "0.5.10"